language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost1.48-dev libboost-test1.48-dev
script:
  - cd lab
  - make
  - make clean
  - make remove_comments
  - cp ../solution/* .
  - make
