language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install libboost1.48-dev libboost-test1.48-dev
script:
  # Test that the TOC of the description is up to date
  - tools/gen_toc -i README.md -o - | diff README.md -
  # Test the lab environment
  - cd lab
  - make
  # Test the solutions
  - make clean
  - make remove_comments
  - cp ../solution/* .
  - make
